// Mocks generated by Mockito 5.4.5 from annotations
// in caelum/test/data/repositories/weather_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:caelum/core/network/network_info.dart' as _i7;
import 'package:caelum/data/datasources/weather_remote_data_source.dart' as _i5;
import 'package:caelum/data/models/forecast_model.dart' as _i2;
import 'package:caelum/data/models/location_model.dart' as _i3;
import 'package:geolocator_platform_interface/src/enums/enums.dart' as _i9;
import 'package:geolocator_platform_interface/src/geolocator_platform_interface.dart'
    as _i8;
import 'package:geolocator_platform_interface/src/models/models.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForecastModel_0 extends _i1.SmartFake implements _i2.ForecastModel {
  _FakeForecastModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationModel_1 extends _i1.SmartFake implements _i3.LocationModel {
  _FakeLocationModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosition_2 extends _i1.SmartFake implements _i4.Position {
  _FakePosition_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i5.WeatherRemoteDataSource {
  MockWeatherRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ForecastModel> getForecast(_i3.LocationModel? location) =>
      (super.noSuchMethod(
            Invocation.method(#getForecast, [location]),
            returnValue: _i6.Future<_i2.ForecastModel>.value(
              _FakeForecastModel_0(
                this,
                Invocation.method(#getForecast, [location]),
              ),
            ),
          )
          as _i6.Future<_i2.ForecastModel>);

  @override
  _i6.Future<_i2.ForecastModel> getForecastByCity(String? city) =>
      (super.noSuchMethod(
            Invocation.method(#getForecastByCity, [city]),
            returnValue: _i6.Future<_i2.ForecastModel>.value(
              _FakeForecastModel_0(
                this,
                Invocation.method(#getForecastByCity, [city]),
              ),
            ),
          )
          as _i6.Future<_i2.ForecastModel>);

  @override
  _i6.Future<_i3.LocationModel> getLocationByCity(String? city) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationByCity, [city]),
            returnValue: _i6.Future<_i3.LocationModel>.value(
              _FakeLocationModel_1(
                this,
                Invocation.method(#getLocationByCity, [city]),
              ),
            ),
          )
          as _i6.Future<_i3.LocationModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [GeolocatorPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeolocatorPlatform extends _i1.Mock
    implements _i8.GeolocatorPlatform {
  MockGeolocatorPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i9.LocationPermission> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i6.Future<_i9.LocationPermission>.value(
              _i9.LocationPermission.denied,
            ),
          )
          as _i6.Future<_i9.LocationPermission>);

  @override
  _i6.Future<_i9.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i6.Future<_i9.LocationPermission>.value(
              _i9.LocationPermission.denied,
            ),
          )
          as _i6.Future<_i9.LocationPermission>);

  @override
  _i6.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i4.Position?> getLastKnownPosition({
    bool? forceLocationManager = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLastKnownPosition, [], {
              #forceLocationManager: forceLocationManager,
            }),
            returnValue: _i6.Future<_i4.Position?>.value(),
          )
          as _i6.Future<_i4.Position?>);

  @override
  _i6.Future<_i4.Position> getCurrentPosition({
    _i4.LocationSettings? locationSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, [], {
              #locationSettings: locationSettings,
            }),
            returnValue: _i6.Future<_i4.Position>.value(
              _FakePosition_2(
                this,
                Invocation.method(#getCurrentPosition, [], {
                  #locationSettings: locationSettings,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Position>);

  @override
  _i6.Stream<_i9.ServiceStatus> getServiceStatusStream() =>
      (super.noSuchMethod(
            Invocation.method(#getServiceStatusStream, []),
            returnValue: _i6.Stream<_i9.ServiceStatus>.empty(),
          )
          as _i6.Stream<_i9.ServiceStatus>);

  @override
  _i6.Stream<_i4.Position> getPositionStream({
    _i4.LocationSettings? locationSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, [], {
              #locationSettings: locationSettings,
            }),
            returnValue: _i6.Stream<_i4.Position>.empty(),
          )
          as _i6.Stream<_i4.Position>);

  @override
  _i6.Future<_i9.LocationAccuracyStatus> requestTemporaryFullAccuracy({
    required String? purposeKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestTemporaryFullAccuracy, [], {
              #purposeKey: purposeKey,
            }),
            returnValue: _i6.Future<_i9.LocationAccuracyStatus>.value(
              _i9.LocationAccuracyStatus.reduced,
            ),
          )
          as _i6.Future<_i9.LocationAccuracyStatus>);

  @override
  _i6.Future<_i9.LocationAccuracyStatus> getLocationAccuracy() =>
      (super.noSuchMethod(
            Invocation.method(#getLocationAccuracy, []),
            returnValue: _i6.Future<_i9.LocationAccuracyStatus>.value(
              _i9.LocationAccuracyStatus.reduced,
            ),
          )
          as _i6.Future<_i9.LocationAccuracyStatus>);

  @override
  _i6.Future<bool> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> openLocationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettings, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  double distanceBetween(
    double? startLatitude,
    double? startLongitude,
    double? endLatitude,
    double? endLongitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#distanceBetween, [
              startLatitude,
              startLongitude,
              endLatitude,
              endLongitude,
            ]),
            returnValue: 0.0,
          )
          as double);

  @override
  double bearingBetween(
    double? startLatitude,
    double? startLongitude,
    double? endLatitude,
    double? endLongitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bearingBetween, [
              startLatitude,
              startLongitude,
              endLatitude,
              endLongitude,
            ]),
            returnValue: 0.0,
          )
          as double);
}
